version: "3.9"

services:
  backend:
    build: ./backend
    container_name: backend
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://apfm-mysql.mysql.database.azure.com:3306/apfmdb?useSSL=true
      SPRING_DATASOURCE_USERNAME: adminuser
      SPRING_DATASOURCE_PASSWORD: MyPassword123!
      SPRING_REDIS_HOST: apfm-redis.redis.cache.windows.net
      SPRING_REDIS_PORT: 6380
      SPRING_REDIS_PASSWORD: <PrimaryKey>
    depends_on:
      - frontend
      - fastapi

  frontend:
    build: ./front
    container_name: front
    ports:
      - "80:80"

  fastapi:
    build: ./AI
    container_name: fastapi
    ports:
      - "8000:8000"
