apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: apfm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: apfmrg.azurecr.io/dnjsdnapfm-backend:latest   # ✅ Backend 이미지
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: apfm
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 8082
      targetPort: 8082
