apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: apfm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: apfmrg.azurecr.io/dnjsdnapfm-frontend:latest   # ✅ Frontend 이미지
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: apfm
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
