apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: apfm
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: apfmrg.azurecr.io/dnjsdnapfm-frontend:latest
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: apfm
spec:
  type: LoadBalancer          # ✅ 외부에서 접속 가능
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
