# [기능 요약] FastAPI 외부 노출(LoadBalancer)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: apfm
spec:
  replicas: 1
  selector:
    matchLabels: { app: fastapi }
  template:
    metadata:
      labels: { app: fastapi }
    spec:
      containers:
        - name: fastapi
          # 필요한 import(이미지): ACR 경로 최신 반영
          image: apfmrg.azurecr.io/fastapi:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "2Gi"
              cpu: "500m"
            limits:
              memory: "4Gi"
              cpu: "1"
          readinessProbe:
            httpGet: { path: /health, port: 8080 }
            initialDelaySeconds: 300
            timeoutSeconds: 30
            periodSeconds: 15
            failureThreshold: 5
          livenessProbe:
            httpGet: { path: /health, port: 8080 }
            initialDelaySeconds: 300
            timeoutSeconds: 30
            periodSeconds: 15
            failureThreshold: 5
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi
  namespace: apfm
spec:
  type: ClusterIP
  selector:
    app: fastapi
  ports:
    - port: 8000
      targetPort: 8000
