# [기능 요약] React 정적 사이트(Nginx) 배포 및 외부 노출(LoadBalancer)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: apfm
spec:
  replicas: 1
  selector:
    matchLabels: { app: frontend }
  template:
    metadata:
      labels: { app: frontend }
    spec:
      containers:
        - name: frontend
          # 필요한 import(이미지): ACR에 올린 경로 반영
          image: apfmregistry.azurecr.io/front:latest
          ports:
            - containerPort: 80
          # (선택) 헬스체크 필요 시 간단히 루트로
          readinessProbe:
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 5
          livenessProbe:
            httpGet: { path: /, port: 80 }
            initialDelaySeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: apfm
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
